//! The format's string enumerations.
//!
//! Every one is generated by `str_enum!`, which gives each a serde representation
//! plus a **fallback variant**. That fallback is deliberate: the spec says a loader
//! should tolerate an enum member a future version adds — treat an unknown
//! `process.kind` as `other` and an unknown `role` as `data` — rather than drop the
//! record. Deriving `Deserialize` cannot express that, since serde's `other`
//! attribute applies only to internally tagged enums.

use serde::de::{Deserialize, Deserializer};
use serde::ser::{Serialize, Serializer};

macro_rules! str_enum {
    (
        $(#[$meta:meta])*
        $name:ident, fallback = $fallback:ident, {
            $($variant:ident => $text:literal),* $(,)?
        }
    ) => {
        $(#[$meta])*
        #[derive(Clone, Copy, PartialEq, Eq, Debug)]
        pub enum $name {
            $($variant,)*
        }

        impl $name {
            pub const fn as_str(self) -> &'static str {
                match self {
                    $(Self::$variant => $text,)*
                }
            }

            /// Parse, falling back to the tolerant variant on anything unknown.
            pub fn parse(text: &str) -> Self {
                match text {
                    $($text => Self::$variant,)*
                    _ => Self::$fallback,
                }
            }
        }

        impl core::fmt::Display for $name {
            fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                f.write_str(self.as_str())
            }
        }

        impl Serialize for $name {
            fn serialize<S: Serializer>(&self, s: S) -> Result<S::Ok, S::Error> {
                s.serialize_str(self.as_str())
            }
        }

        impl<'de> Deserialize<'de> for $name {
            fn deserialize<D: Deserializer<'de>>(d: D) -> Result<Self, D::Error> {
                let text = std::borrow::Cow::<str>::deserialize(d)?;
                Ok(Self::parse(&text))
            }
        }
    };
}

str_enum!(
    /// Source language of a file, unit or design.
    Language, fallback = Other, {
        Verilog => "verilog",
        SystemVerilog => "systemverilog",
        Vhdl => "vhdl",
        SpinalHdl => "spinalhdl",
        Chisel => "chisel",
        Spade => "spade",
        Other => "other",
    }
);

str_enum!(
    /// What a scope definition represents.
    UnitKind, fallback = Other, {
        Module => "module",
        Interface => "interface",
        Program => "program",
        Package => "package",
        Class => "class",
        Udp => "udp",
        GenBlock => "genBlock",
        Block => "block",
        Function => "function",
        Task => "task",
        StructScope => "structScope",
        ArrayScope => "arrayScope",
        VhdlArchitecture => "vhdlArchitecture",
        VhdlProcess => "vhdlProcess",
        VhdlBlock => "vhdlBlock",
        VhdlGenerate => "vhdlGenerate",
        VhdlPackage => "vhdlPackage",
        VhdlRecord => "vhdlRecord",
        VhdlProcedure => "vhdlProcedure",
        VhdlFunction => "vhdlFunction",
        BlackBox => "blackBox",
        Other => "other",
    }
);

impl UnitKind {
    /// True for the scope kinds a `ref.up` hop may cross. A module, interface or
    /// program boundary is opaque, which is what `conns` exists for.
    pub const fn is_block(self) -> bool {
        matches!(
            self,
            Self::GenBlock
                | Self::Block
                | Self::Function
                | Self::Task
                | Self::StructScope
                | Self::ArrayScope
        )
    }
}

str_enum!(
    /// What kind of child scope an instance creates.
    InstanceKind, fallback = Other, {
        Instance => "instance",
        GenBlock => "genBlock",
        Block => "block",
        Function => "function",
        Task => "task",
        StructScope => "structScope",
        ArrayScope => "arrayScope",
        Interface => "interface",
        Package => "package",
        Other => "other",
    }
);

str_enum!(
    /// The structural shape of a type.
    TypeKind, fallback = Opaque, {
        Bits => "bits",
        Enum => "enum",
        Struct => "struct",
        Union => "union",
        PackedArray => "packedArray",
        UnpackedArray => "unpackedArray",
        Alias => "alias",
        Real => "real",
        Str => "string",
        Event => "event",
        Void => "void",
        Chandle => "chandle",
        Class => "class",
        Interface => "interface",
        Opaque => "opaque",
    }
);

impl TypeKind {
    /// Kinds the schema requires a `width` on.
    pub const fn needs_width(self) -> bool {
        matches!(self, Self::Bits | Self::Enum | Self::Real | Self::PackedArray)
    }
}

str_enum!(
    /// Unpacked collection shape.
    ArrayShape, fallback = Fixed, {
        Fixed => "fixed",
        Dynamic => "dynamic",
        Queue => "queue",
        Assoc => "assoc",
    }
);

str_enum!(
    /// How a variable is driven — the container, not the value type.
    VarKind, fallback = Other, {
        Net => "net",
        Var => "var",
        Param => "param",
        Genvar => "genvar",
        Memory => "memory",
        Port => "port",
        Alias => "alias",
        Other => "other",
    }
);

str_enum!(
    /// Port direction. `Internal` means "not a port".
    Direction, fallback = Internal, {
        Input => "input",
        Output => "output",
        Inout => "inout",
        Ref => "ref",
        Internal => "internal",
    }
);

impl Direction {
    pub const fn is_port(self) -> bool {
        !matches!(self, Self::Internal)
    }
    /// An input or inout is driven from the parent, so its driver lives there.
    pub const fn driven_from_parent(self) -> bool {
        matches!(self, Self::Input | Self::Inout)
    }
}

str_enum!(
    /// The RTL construct a process came from.
    ProcessKind, fallback = Other, {
        ContAssign => "contAssign",
        AlwaysComb => "alwaysComb",
        AlwaysFf => "alwaysFF",
        AlwaysLatch => "alwaysLatch",
        Always => "always",
        Initial => "initial",
        Final => "final",
        Assertion => "assertion",
        VhdlProcess => "vhdlProcess",
        VhdlConcurrent => "vhdlConcurrent",
        Primitive => "primitive",
        Other => "other",
    }
);

impl ProcessKind {
    /// Sequential by construct, before the sensitivity list is consulted.
    pub const fn is_sequential(self) -> bool {
        matches!(self, Self::AlwaysFf | Self::AlwaysLatch)
    }
}

str_enum!(
    /// Why a reference participates in a write.
    RefRole, fallback = Data, {
        Data => "data",
        Control => "control",
        Clock => "clock",
        Reset => "reset",
        Enable => "enable",
        Index => "index",
    }
);

str_enum!(
    /// Edge sensitivity. `Pos`/`Neg` are what make a process sequential.
    Edge, fallback = Any, {
        Pos => "pos",
        Neg => "neg",
        Any => "any",
        Level => "level",
    }
);

impl Edge {
    pub const fn is_edge(self) -> bool {
        matches!(self, Self::Pos | Self::Neg)
    }
}

str_enum!(
    /// Semantic role of a sensitivity entry.
    SenseRole, fallback = Data, {
        Clock => "clock",
        Reset => "reset",
        Enable => "enable",
        Data => "data",
    }
);

str_enum!(
    /// Presentation hint a producer may offer; the sidecar always overrides it.
    HintRole, fallback = Data, {
        Clock => "clock",
        Reset => "reset",
        Enable => "enable",
        Valid => "valid",
        Ready => "ready",
        Data => "data",
    }
);

str_enum!(
    /// Asserted level of an active-level signal.
    Polarity, fallback = ActiveHigh, {
        ActiveHigh => "activeHigh",
        ActiveLow => "activeLow",
    }
);

str_enum!(
    /// Suggested default radix.
    Radix, fallback = Hex, {
        Bin => "bin",
        Hex => "hex",
        Dec => "dec",
        Sdec => "sdec",
        Enum => "enum",
    }
);

str_enum!(
    /// Completeness claim for the tree axis. Absent means "not claimed".
    TreeFidelity, fallback = Complete, { Complete => "complete" }
);

str_enum!(
    /// Completeness claim for the type axis. Absent means "not claimed".
    TypeFidelity, fallback = Declared, { Declared => "declared" }
);

str_enum!(
    /// Completeness claim for driver recording and for the cone graph.
    Coverage, fallback = Partial, {
        Partial => "partial",
        Complete => "complete",
    }
);

str_enum!(
    /// Completeness claim for bit-range exactness. Absent means "not claimed".
    BitsFidelity, fallback = Exact, { Exact => "exact" }
);

str_enum!(
    /// How escaped identifiers appear in the trace.
    EscapeStyle, fallback = None, {
        None => "none",
        Verilog => "verilog",
    }
);

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn round_trips_through_json() {
        let json = serde_json::to_string(&ProcessKind::AlwaysFf).unwrap();
        assert_eq!(json, "\"alwaysFF\"");
        assert_eq!(
            serde_json::from_str::<ProcessKind>(&json).unwrap(),
            ProcessKind::AlwaysFf
        );
    }

    #[test]
    fn unknown_members_fall_back_instead_of_failing() {
        // The spec requires tolerance: a future `process.kind` must not drop the record.
        assert_eq!(
            serde_json::from_str::<ProcessKind>("\"alwaysFuture\"").unwrap(),
            ProcessKind::Other
        );
        assert_eq!(
            serde_json::from_str::<RefRole>("\"telepathy\"").unwrap(),
            RefRole::Data
        );
        assert_eq!(
            serde_json::from_str::<TypeKind>("\"quantum\"").unwrap(),
            TypeKind::Opaque
        );
    }

    #[test]
    fn block_kinds_are_the_ones_up_may_cross() {
        assert!(UnitKind::GenBlock.is_block());
        assert!(UnitKind::Function.is_block());
        assert!(!UnitKind::Module.is_block());
        assert!(!UnitKind::Interface.is_block());
    }
}
